#include <seal/seal.h>
#include <iostream>
#include <vector>
#include <chrono>
#include <fstream>
#include <ctime>
#include <iomanip>
#include <algorithm>
#include <numeric>
#include <omp.h>
#include <atomic>

using namespace std;
using namespace seal;

/*******************************************
 * CONSTANTS
 *******************************************/
static const uint64_t PLAIN_MOD = 257;
static const uint64_t INV2 = 129;  // inverse of 2 mod 257

// Q(y) coefficients: sign(x) = x * Q(x^2) over Z_257
// 128 coefficients (degree 127 polynomial)
// Generated by compute_sign_poly.py
static const uint64_t Q_COEFFS[128] = {
    129, 189, 142,  98,  50,  17,  95, 247,
      0, 239, 101, 199,  92, 224,  16, 111,
      0, 153,  36,  93,  61,  93, 199,  87,
      0, 100, 148,  10, 136,  86, 151, 204,
      0, 240, 140, 191, 132,   1,  82, 245,
      0, 157,   8, 192, 102, 230,   0,  65,
      0, 238, 214,   3, 136,  43,  30,  35,
      0, 159,  96, 116, 193, 101, 164, 206,
      0, 116,  73, 188, 187, 172, 115,  96,
      0, 184, 169, 177, 118, 104,  56, 207,
      0,  49, 221,  83, 125,   8, 124, 209,
      0, 192,  91, 204, 216, 187,  97,  16,
      0, 104, 248,  52,  50, 157,  58,  46,
      0, 252, 115, 132,  80,   4,   6,  71,
      0, 236, 178,  26, 224,   5, 240,  82,
      0, 256, 126, 185, 197, 253,   8, 193
};

static const size_t Q_SIZE = 128;
static const size_t BABY_STEP = 8;
static const size_t NUM_GROUPS = Q_SIZE / BABY_STEP;  // 16

/*******************************************
 * GLOBAL COUNTERS
 *******************************************/
static atomic<size_t> ct_ct_mult_count{0};

/*******************************************
 * HELPERS
 *******************************************/

// Encode a single scalar value as a SEAL Plaintext (hex string)
Plaintext make_scalar_plain(uint64_t v) {
    v = v % PLAIN_MOD;
    stringstream ss;
    ss << hex << v;
    return Plaintext(ss.str());
}

// Multiply ciphertext by ciphertext, relinearize, track count
void ct_mult(Evaluator &eval, const Ciphertext &a, const Ciphertext &b,
             Ciphertext &dest, const RelinKeys &rlk) {
    eval.multiply(a, b, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

// Square ciphertext, relinearize, track count
void ct_square(Evaluator &eval, const Ciphertext &a,
               Ciphertext &dest, const RelinKeys &rlk) {
    eval.square(a, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

/*******************************************
 * PATERSON-STOCKMEYER EVALUATION
 *
 * Shared helper: evaluates Q(y) where y = diff^2
 * using Paterson-Stockmeyer with baby step s=8.
 *
 * Returns {T, y} where T = Q(y) and y = diff^2.
 *
 * Q has 128 coefficients, baby step s=8, 16 giant groups.
 *******************************************/
pair<Ciphertext, Ciphertext> eval_Q_of_y(Evaluator &eval,
                                          const Ciphertext &diff,
                                          const RelinKeys &rlk) {
    //--- Phase 1: Baby powers of y = diff^2 ---
    Ciphertext y;  // y = diff^2
    ct_square(eval, diff, y, rlk);

    Ciphertext y2, y3, y4, y5, y6, y7, z;

    ct_square(eval, y, y2, rlk);          // y^2, depth 2 from diff
    ct_mult(eval, y, y2, y3, rlk);        // y^3, depth 3
    ct_square(eval, y2, y4, rlk);         // y^4, depth 3
    ct_mult(eval, y, y4, y5, rlk);        // y^5, depth 4
    ct_mult(eval, y2, y4, y6, rlk);       // y^6, depth 4
    ct_mult(eval, y3, y4, y7, rlk);       // y^7, depth 4
    ct_square(eval, y4, z, rlk);          // y^8 = z, depth 4

    vector<Ciphertext*> baby = {&y, &y2, &y3, &y4, &y5, &y6, &y7};

    //--- Phase 2: Compute B_i groups ---
    vector<Ciphertext> B(NUM_GROUPS);

    for (size_t i = 0; i < NUM_GROUPS; i++) {
        size_t base = i * BABY_STEP;
        bool initialized = false;

        for (size_t j = 0; j < BABY_STEP; j++) {
            uint64_t coeff = Q_COEFFS[base + j];
            if (coeff == 0) continue;

            if (j == 0) {
                if (!initialized) {
                    continue;
                }
            } else {
                Ciphertext term;
                eval.multiply_plain(*baby[j - 1], make_scalar_plain(coeff), term);

                if (!initialized) {
                    B[i] = term;
                    initialized = true;
                } else {
                    eval.add_inplace(B[i], term);
                }
            }
        }

        uint64_t const_coeff = Q_COEFFS[base];
        if (const_coeff != 0) {
            if (!initialized) {
                B[i] = y;  // copy
                eval.sub_inplace(B[i], y);  // B[i] = 0 (as ciphertext)
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
                initialized = true;
            } else {
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
            }
        }

        if (!initialized) {
            B[i] = y;
            eval.sub_inplace(B[i], y);
        }
    }

    //--- Phase 3: Estrin tree to combine B_i using giant step z = y^8 ---
    // Level 0
    vector<Ciphertext> P(8);
    for (size_t j = 0; j < 8; j++) {
        ct_mult(eval, z, B[2 * j + 1], P[j], rlk);
        eval.add_inplace(P[j], B[2 * j]);
    }

    Ciphertext z2;
    ct_square(eval, z, z2, rlk);

    // Level 1
    vector<Ciphertext> R(4);
    for (size_t j = 0; j < 4; j++) {
        ct_mult(eval, z2, P[2 * j + 1], R[j], rlk);
        eval.add_inplace(R[j], P[2 * j]);
    }

    Ciphertext z4;
    ct_square(eval, z2, z4, rlk);

    // Level 2
    vector<Ciphertext> S(2);
    for (size_t j = 0; j < 2; j++) {
        ct_mult(eval, z4, R[2 * j + 1], S[j], rlk);
        eval.add_inplace(S[j], R[2 * j]);
    }

    Ciphertext z8;
    ct_square(eval, z4, z8, rlk);

    // Level 3
    Ciphertext T;
    ct_mult(eval, z8, S[1], T, rlk);
    eval.add_inplace(T, S[0]);

    return {T, y};
}

/*******************************************
 * CORRECTION POLYNOMIAL
 *
 * correction = 129 * (diff + y * Q(y))
 * Returns diff if diff in {1,...,128}, 0 otherwise
 *******************************************/
Ciphertext eval_correction_poly(Evaluator &eval,
                                const Ciphertext &diff,
                                const RelinKeys &rlk) {
    auto [T, y] = eval_Q_of_y(eval, diff, rlk);

    Ciphertext yQ;
    ct_mult(eval, y, T, yQ, rlk);  // y * Q(y)

    Ciphertext inner;
    eval.add(diff, yQ, inner);  // diff + y * Q(y)

    Ciphertext correction;
    eval.multiply_plain(inner, make_scalar_plain(INV2), correction);

    return correction;
}

/*******************************************
 * COMPARE AND SWAP (ascending)
 *
 * If a > b: sets a = b, b = a (swap)
 * If a <= b: no change
 *******************************************/
void compare_and_swap(Evaluator &eval,
                      Ciphertext &ct_a, Ciphertext &ct_b,
                      const RelinKeys &rlk) {
    Ciphertext diff;
    eval.sub(ct_a, ct_b, diff);  // diff = a - b

    Ciphertext correction = eval_correction_poly(eval, diff, rlk);

    eval.sub_inplace(ct_a, correction);  // a - correction = min(a,b) if a>b
    eval.add_inplace(ct_b, correction);  // b + correction = max(a,b) if a>b
}

/*******************************************
 * BITONIC SORT (OpenMP parallelized)
 *
 * Standard bitonic sorting network.
 * Pairs within each round operate on disjoint
 * elements and are parallelized with OpenMP.
 * Rounds remain sequential (each depends on
 * previous round's output).
 *******************************************/
void bitonic_sort(Evaluator &eval,
                  vector<Ciphertext> &ct,
                  const RelinKeys &rlk,
                  Decryptor &decryptor) {
    size_t n = ct.size();
    int round = 0;

    for (size_t k = 2; k <= n; k <<= 1) {
        for (size_t j = k >> 1; j >= 1; j >>= 1) {
            round++;
            cout << "  Round " << round << " (k=" << k << ", j=" << j << "):" << endl;

            // Collect CAS pairs for this round
            vector<pair<size_t, size_t>> pairs;
            vector<bool> ascending_vec;
            for (size_t i = 0; i < n; i++) {
                size_t l = i ^ j;
                if (l > i) {
                    pairs.push_back({i, l});
                    ascending_vec.push_back((i & k) == 0);
                }
            }

            #pragma omp parallel for schedule(static)
            for (size_t p = 0; p < pairs.size(); p++) {
                size_t i = pairs[p].first;
                size_t l = pairs[p].second;
                if (ascending_vec[p])
                    compare_and_swap(eval, ct[i], ct[l], rlk);
                else
                    compare_and_swap(eval, ct[l], ct[i], rlk);
            }

            // Print noise budget after each round (after implicit barrier)
            cout << "    Noise budgets: ";
            for (size_t i = 0; i < n; i++) {
                cout << decryptor.invariant_noise_budget(ct[i]);
                if (i < n - 1) cout << ", ";
            }
            cout << " bits" << endl;
        }
    }
}

/*******************************************
 * RUN ONE BENCHMARK
 *******************************************/
void run_benchmark(const vector<uint64_t> &input_values,
                   Encryptor &encryptor,
                   Evaluator &evaluator,
                   Decryptor &decryptor,
                   const RelinKeys &relin_keys) {
    size_t n = input_values.size();
    string algo_name = "BitonicBFV_NonBatched_Parallel";

    cout << "\n========================================" << endl;
    cout << "Sorting " << n << " encrypted values (" << algo_name << ")" << endl;
    cout << "========================================" << endl;

    // Verify all values are in valid range [0, 128]
    for (auto v : input_values) {
        if (v > 128) {
            cerr << "ERROR: Value " << v << " exceeds max 128!" << endl;
            return;
        }
    }

    // Encrypt
    cout << "  Input:  ";
    for (auto v : input_values) cout << v << " ";
    cout << endl;

    vector<Ciphertext> ct(n);
    for (size_t i = 0; i < n; i++) {
        encryptor.encrypt(make_scalar_plain(input_values[i]), ct[i]);
    }

    cout << "  Initial noise budget: " << decryptor.invariant_noise_budget(ct[0]) << " bits" << endl;

    // Sort
    ct_ct_mult_count = 0;
    auto sort_start = chrono::high_resolution_clock::now();
    bitonic_sort(evaluator, ct, relin_keys, decryptor);
    auto sort_end = chrono::high_resolution_clock::now();

    auto sort_ms = chrono::duration_cast<chrono::milliseconds>(sort_end - sort_start).count();
    size_t mults = ct_ct_mult_count;

    // Decrypt and verify
    vector<uint64_t> output(n);
    for (size_t i = 0; i < n; i++) {
        Plaintext pt;
        decryptor.decrypt(ct[i], pt);
        output[i] = (pt.coeff_count() > 0) ? pt[0] : 0;
    }

    cout << "  Output: ";
    for (auto v : output) cout << v << " ";
    cout << endl;

    vector<uint64_t> expected = input_values;
    sort(expected.begin(), expected.end());

    bool correct = (output == expected);
    cout << "  " << (correct ? "PASS" : "FAIL") << endl;

    // Find min noise budget
    long min_noise = decryptor.invariant_noise_budget(ct[0]);
    for (size_t i = 1; i < n; i++) {
        long nb = decryptor.invariant_noise_budget(ct[i]);
        if (nb < min_noise) min_noise = nb;
    }

    cout << "  Sort time:        " << sort_ms << " ms" << endl;
    cout << "  Ct-ct multiplies: " << mults << endl;
    cout << "  Min noise budget: " << min_noise << " bits" << endl;

    // CSV logging
    time_t now = time(nullptr);
    tm *local_time = localtime(&now);
    ostringstream timestamp;
    timestamp << put_time(local_time, "%Y-%m-%d %H:%M:%S");

    ofstream csv("benchmark_results.csv", ios::app);
    csv.seekp(0, ios::end);
    if (csv.tellp() == 0) {
        csv << "timestamp,algorithm,n,runtime_ms,ct_ct_multiplications,noise_budget_bits,correct\n";
    }

    csv << timestamp.str() << ","
        << algo_name << ","
        << n << ","
        << sort_ms << ","
        << mults << ","
        << min_noise << ","
        << (correct ? "true" : "false") << "\n";
    csv.close();
}

/*******************************************
 * MAIN
 *******************************************/
int main() {
    cout << "========================================" << endl;
    cout << "Bitonic BFV Sort (OpenMP Parallel)" << endl;
    cout << "========================================" << endl;
    cout << "OpenMP threads: " << omp_get_max_threads() << endl;

    /*********************
     * BFV PARAMETER SETUP
     *********************/
    cout << "\n[1] Setting up BFV parameters..." << endl;

    size_t poly_modulus_degree = 32768;

    EncryptionParameters parms(scheme_type::bfv);
    parms.set_poly_modulus_degree(poly_modulus_degree);
    // Bitonic sort: depth ~90 at n=16, needs large noise budget.
    // 40 primes x 60 bits = 2400 bits.
    // N=32768 required for this many primes.
    parms.set_coeff_modulus(CoeffModulus::Create(poly_modulus_degree,
        {60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60}));
    parms.set_plain_modulus(PLAIN_MOD);

    SEALContext context(parms, true, sec_level_type::none);

    auto context_data = context.key_context_data();
    if (!context_data) {
        cerr << "ERROR: Invalid parameters!" << endl;
        return 1;
    }

    auto &ctx_parms = context_data->parms();
    auto &coeff_mod = ctx_parms.coeff_modulus();
    size_t total_bits = 0;
    for (auto &m : coeff_mod) total_bits += m.bit_count();
    cout << "    poly_modulus_degree = " << poly_modulus_degree << endl;
    cout << "    plain_modulus = " << PLAIN_MOD << endl;
    cout << "    coeff_modulus total bits: " << total_bits << endl;

    /*********************
     * KEY GENERATION
     *********************/
    cout << "\n[2] Generating keys..." << endl;

    auto key_start = chrono::high_resolution_clock::now();

    KeyGenerator keygen(context);
    auto secret_key = keygen.secret_key();

    PublicKey public_key;
    keygen.create_public_key(public_key);

    RelinKeys relin_keys;
    keygen.create_relin_keys(relin_keys);

    auto key_end = chrono::high_resolution_clock::now();
    auto key_ms = chrono::duration_cast<chrono::milliseconds>(key_end - key_start).count();
    cout << "    Key generation done (" << key_ms << " ms)" << endl;

    Encryptor encryptor(context, public_key);
    Evaluator evaluator(context);
    Decryptor decryptor(context, secret_key);

    /*********************
     * SINGLE CAS SANITY CHECK
     *********************/
    cout << "\n[3] Quick test: single compare-and-swap on (42, 17)..." << endl;
    {
        Ciphertext test_a, test_b;
        encryptor.encrypt(make_scalar_plain(42), test_a);
        encryptor.encrypt(make_scalar_plain(17), test_b);

        ct_ct_mult_count = 0;
        compare_and_swap(evaluator, test_a, test_b, relin_keys);

        Plaintext pt_a, pt_b;
        decryptor.decrypt(test_a, pt_a);
        decryptor.decrypt(test_b, pt_b);

        uint64_t val_a = (pt_a.coeff_count() > 0) ? pt_a[0] : 0;
        uint64_t val_b = (pt_b.coeff_count() > 0) ? pt_b[0] : 0;

        cout << "    Result: (" << val_a << ", " << val_b << ") — "
             << ((val_a == 17 && val_b == 42) ? "PASS" : "FAIL") << endl;
        cout << "    Ct-ct multiplications per CAS: " << ct_ct_mult_count << endl;
        cout << "    Noise budget after CAS: "
             << decryptor.invariant_noise_budget(test_a) << " bits" << endl;
    }

    /*********************
     * BENCHMARK: Bitonic sort n=2,4,8,16
     *********************/
    run_benchmark({42, 17},
                  encryptor, evaluator, decryptor, relin_keys);

    run_benchmark({42, 17, 83, 5},
                  encryptor, evaluator, decryptor, relin_keys);

    run_benchmark({42, 17, 83, 5, 91, 33, 67, 12},
                  encryptor, evaluator, decryptor, relin_keys);

    run_benchmark({42, 17, 83, 5, 91, 33, 67, 12, 100, 2, 55, 28, 76, 9, 118, 44},
                  encryptor, evaluator, decryptor, relin_keys);

    cout << "\nAll benchmarks complete. Results in benchmark_results.csv" << endl;

    return 0;
}
