#include <seal/seal.h>
#include <iostream>
#include <vector>
#include <chrono>
#include <fstream>
#include <ctime>
#include <iomanip>
#include <algorithm>
#include <numeric>

using namespace std;
using namespace seal;

/*******************************************
 * CONSTANTS
 *******************************************/
static const uint64_t PLAIN_MOD = 257;
static const uint64_t INV2 = 129;  // inverse of 2 mod 257

// Q(y) coefficients: sign(x) = x * Q(x^2) over Z_257
// 128 coefficients (degree 127 polynomial)
// Generated by compute_sign_poly.py
static const uint64_t Q_COEFFS[128] = {
    129, 189, 142,  98,  50,  17,  95, 247,
      0, 239, 101, 199,  92, 224,  16, 111,
      0, 153,  36,  93,  61,  93, 199,  87,
      0, 100, 148,  10, 136,  86, 151, 204,
      0, 240, 140, 191, 132,   1,  82, 245,
      0, 157,   8, 192, 102, 230,   0,  65,
      0, 238, 214,   3, 136,  43,  30,  35,
      0, 159,  96, 116, 193, 101, 164, 206,
      0, 116,  73, 188, 187, 172, 115,  96,
      0, 184, 169, 177, 118, 104,  56, 207,
      0,  49, 221,  83, 125,   8, 124, 209,
      0, 192,  91, 204, 216, 187,  97,  16,
      0, 104, 248,  52,  50, 157,  58,  46,
      0, 252, 115, 132,  80,   4,   6,  71,
      0, 236, 178,  26, 224,   5, 240,  82,
      0, 256, 126, 185, 197, 253,   8, 193
};

static const size_t Q_SIZE = 128;
static const size_t BABY_STEP = 8;
static const size_t NUM_GROUPS = Q_SIZE / BABY_STEP;  // 16

/*******************************************
 * GLOBAL COUNTERS
 *******************************************/
static size_t ct_ct_mult_count = 0;

/*******************************************
 * HELPERS
 *******************************************/

// Encode a single scalar value as a SEAL Plaintext (hex string)
Plaintext make_scalar_plain(uint64_t v) {
    v = v % PLAIN_MOD;
    // SEAL expects hex-encoded polynomial coefficients
    // For a scalar, just the constant term
    stringstream ss;
    ss << hex << v;
    return Plaintext(ss.str());
}

// Multiply ciphertext by ciphertext, relinearize, track count
void ct_mult(Evaluator &eval, const Ciphertext &a, const Ciphertext &b,
             Ciphertext &dest, const RelinKeys &rlk) {
    eval.multiply(a, b, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

// Square ciphertext, relinearize, track count
void ct_square(Evaluator &eval, const Ciphertext &a,
               Ciphertext &dest, const RelinKeys &rlk) {
    eval.square(a, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

/*******************************************
 * PATERSON-STOCKMEYER EVALUATION
 *
 * Evaluates Q(y) where y = diff^2,
 * then assembles correction = 129 * (diff + y * Q(y))
 *
 * Q has 128 coefficients, baby step s=8, 16 giant groups.
 *******************************************/
Ciphertext eval_correction_poly(Evaluator &eval,
                                const Ciphertext &diff,
                                const RelinKeys &rlk) {
    //--- Phase 1: Baby powers of y = diff^2 ---
    // We need y^0 (implicit), y^1, ..., y^7, and z = y^8
    Ciphertext y;  // y = diff^2
    ct_square(eval, diff, y, rlk);

    // Build baby powers: bp[0] = y, bp[1] = y^2, ..., bp[6] = y^7
    // Using a multiplication tree to minimize depth
    Ciphertext y2, y3, y4, y5, y6, y7, z;

    ct_square(eval, y, y2, rlk);          // y^2, depth 2 from diff
    ct_mult(eval, y, y2, y3, rlk);        // y^3, depth 3
    ct_square(eval, y2, y4, rlk);         // y^4, depth 3
    ct_mult(eval, y, y4, y5, rlk);        // y^5, depth 4
    ct_mult(eval, y2, y4, y6, rlk);       // y^6, depth 4
    ct_mult(eval, y3, y4, y7, rlk);       // y^7, depth 4
    ct_square(eval, y4, z, rlk);          // y^8 = z, depth 4

    // Array of baby powers for convenient indexing
    // baby[k] = y^(k+1) for k=0..6, so baby[k] corresponds to y^(k+1)
    // We also need y^0 = 1, which is just a plaintext addition (no ciphertext needed)
    vector<Ciphertext*> baby = {&y, &y2, &y3, &y4, &y5, &y6, &y7};

    //--- Phase 2: Compute B_i groups ---
    // B_i(y) = Q[8i] + Q[8i+1]*y + Q[8i+2]*y^2 + ... + Q[8i+7]*y^7
    // Each B_i involves only plaintext-ciphertext operations (no depth increase)
    vector<Ciphertext> B(NUM_GROUPS);

    for (size_t i = 0; i < NUM_GROUPS; i++) {
        size_t base = i * BABY_STEP;
        bool initialized = false;

        for (size_t j = 0; j < BABY_STEP; j++) {
            uint64_t coeff = Q_COEFFS[base + j];
            if (coeff == 0) continue;

            if (j == 0) {
                // Constant term: just a plaintext
                if (!initialized) {
                    // We need a ciphertext with value coeff
                    // Use multiply_plain on any baby power then add? No—
                    // We need to start with a plaintext-valued ciphertext.
                    // Actually we can't create an "encrypted constant" without
                    // encrypting. Instead, we'll handle the constant term specially.
                    // For now, mark that we have a constant and add it after.
                    // We'll accumulate all non-constant terms first, then add_plain.

                    // Actually, let's just use add_plain at the end.
                    // Start with the j=0 term as pending constant.
                    // Skip for now, handle below.
                    continue;
                }
            } else {
                // Term: coeff * y^j
                Ciphertext term;
                eval.multiply_plain(*baby[j - 1], make_scalar_plain(coeff), term);

                if (!initialized) {
                    B[i] = term;
                    initialized = true;
                } else {
                    eval.add_inplace(B[i], term);
                }
            }
        }

        // Add constant term (j=0) as plaintext
        uint64_t const_coeff = Q_COEFFS[base];
        if (const_coeff != 0) {
            if (!initialized) {
                // All higher terms were zero, B_i is just a constant.
                // We need a ciphertext. Multiply any baby power by 0 and add const?
                // Better: multiply y by 0 and add const, but multiply_plain by 0 may
                // cause issues. Instead, take y, multiply by the coefficient of the
                // first non-zero higher term... but we just said they're all zero.
                //
                // Edge case: B_i is a pure constant. We can't represent it as a
                // ciphertext without an encryption context. We'll handle this in
                // the Estrin tree by using add_plain instead.
                //
                // For simplicity, let's create a "zero ciphertext" by subtracting
                // a baby power from itself, then add_plain the constant.
                B[i] = y;  // copy
                eval.sub_inplace(B[i], y);  // B[i] = 0 (as ciphertext)
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
                initialized = true;
            } else {
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
            }
        }

        if (!initialized) {
            // Entire group is zero — create zero ciphertext
            B[i] = y;
            eval.sub_inplace(B[i], y);
        }
    }

    //--- Phase 3: Estrin tree to combine B_i using giant step z = y^8 ---
    // We have 16 groups: B[0] + z*B[1] + z^2*B[2] + ... + z^15*B[15]
    // Estrin tree: pair up and combine bottom-up using powers of z
    //
    // Level 0 (8 pairs): P_j = B[2j] + z * B[2j+1], j=0..7
    // Level 1 (4 pairs): R_j = P[2j] + z^2 * P[2j+1], j=0..3
    // Level 2 (2 pairs): S_j = R[2j] + z^4 * R[2j+1], j=0..1
    // Level 3 (1 pair):  T   = S[0]  + z^8 * S[1]

    // Level 0: 8 ct-ct multiplications
    vector<Ciphertext> P(8);
    for (size_t j = 0; j < 8; j++) {
        ct_mult(eval, z, B[2 * j + 1], P[j], rlk);
        eval.add_inplace(P[j], B[2 * j]);
    }

    // Compute z^2
    Ciphertext z2;
    ct_square(eval, z, z2, rlk);

    // Level 1: 4 ct-ct multiplications
    vector<Ciphertext> R(4);
    for (size_t j = 0; j < 4; j++) {
        ct_mult(eval, z2, P[2 * j + 1], R[j], rlk);
        eval.add_inplace(R[j], P[2 * j]);
    }

    // Compute z^4
    Ciphertext z4;
    ct_square(eval, z2, z4, rlk);

    // Level 2: 2 ct-ct multiplications
    vector<Ciphertext> S(2);
    for (size_t j = 0; j < 2; j++) {
        ct_mult(eval, z4, R[2 * j + 1], S[j], rlk);
        eval.add_inplace(S[j], R[2 * j]);
    }

    // Compute z^8
    Ciphertext z8;
    ct_square(eval, z4, z8, rlk);

    // Level 3: 1 ct-ct multiplication
    Ciphertext T;
    ct_mult(eval, z8, S[1], T, rlk);
    eval.add_inplace(T, S[0]);

    // T now holds Q(y)

    //--- Phase 4: Assembly ---
    // correction = 129 * (diff + y * Q(y))
    // = 129 * (diff + diff^2 * Q(diff^2))
    Ciphertext yQ;
    ct_mult(eval, y, T, yQ, rlk);  // y * Q(y)

    Ciphertext inner;
    eval.add(diff, yQ, inner);  // diff + y * Q(y)

    // Multiply by 129 (inv(2) mod 257)
    Ciphertext correction;
    eval.multiply_plain(inner, make_scalar_plain(INV2), correction);

    return correction;
}

/*******************************************
 * COMPARE AND SWAP (ascending)
 *
 * If a > b: sets a = b, b = a (swap)
 * If a <= b: no change
 *
 * Uses correction polynomial:
 *   correction = diff if diff in {1,...,128}
 *   correction = 0    otherwise
 *******************************************/
void compare_and_swap(Evaluator &eval,
                      Ciphertext &ct_a, Ciphertext &ct_b,
                      const RelinKeys &rlk) {
    Ciphertext diff;
    eval.sub(ct_a, ct_b, diff);  // diff = a - b

    Ciphertext correction = eval_correction_poly(eval, diff, rlk);

    eval.sub_inplace(ct_a, correction);  // a - correction = min(a,b) if a>b
    eval.add_inplace(ct_b, correction);  // b + correction = max(a,b) if a>b
}

/*******************************************
 * BITONIC SORT (8 elements)
 *
 * Standard bitonic sorting network:
 * 6 rounds, 4 compare-and-swap per round,
 * 24 total CAS operations.
 *******************************************/
void bitonic_sort(Evaluator &eval,
                  vector<Ciphertext> &ct,
                  const RelinKeys &rlk,
                  Decryptor &decryptor) {
    size_t n = ct.size();
    int round = 0;

    for (size_t k = 2; k <= n; k <<= 1) {
        for (size_t j = k >> 1; j >= 1; j >>= 1) {
            round++;
            cout << "  Round " << round << " (k=" << k << ", j=" << j << "):" << endl;

            for (size_t i = 0; i < n; i++) {
                size_t l = i ^ j;
                if (l > i) {
                    bool ascending = ((i & k) == 0);
                    if (ascending) {
                        compare_and_swap(eval, ct[i], ct[l], rlk);
                    } else {
                        compare_and_swap(eval, ct[l], ct[i], rlk);
                    }
                }
            }

            // Print noise budget after each round
            cout << "    Noise budgets: ";
            for (size_t i = 0; i < n; i++) {
                cout << decryptor.invariant_noise_budget(ct[i]);
                if (i < n - 1) cout << ", ";
            }
            cout << " bits" << endl;
        }
    }
}

/*******************************************
 * MAIN
 *******************************************/
int main() {
    cout << "========================================" << endl;
    cout << "Non-Batched BFV Bitonic Sort (8 values)" << endl;
    cout << "========================================" << endl;

    /*********************
     * BFV PARAMETER SETUP
     *********************/
    cout << "\n[1] Setting up BFV parameters..." << endl;
    cout << "    poly_modulus_degree = 32768" << endl;
    cout << "    plain_modulus = 257" << endl;

    size_t poly_modulus_degree = 32768;

    EncryptionParameters parms(scheme_type::bfv);
    parms.set_poly_modulus_degree(poly_modulus_degree);
    // Need ~1400 bits of noise budget for 6 rounds x ~220 bits/round.
    // BFVDefault(32768) only gives 881 bits (tc128), so we use sec_level_type::none
    // with a larger coeff_modulus. 26 primes x 60 bits = 1560 bits.
    parms.set_coeff_modulus(CoeffModulus::Create(poly_modulus_degree,
        {60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60}));
    parms.set_plain_modulus(PLAIN_MOD);

    // sec_level_type::none bypasses security enforcement — needed because
    // 1560 bits exceeds the tc128 limit of 881 for N=32768.
    // Fine for research/benchmarking.
    SEALContext context(parms, true, sec_level_type::none);

    // Validate parameters
    auto context_data = context.key_context_data();
    if (!context_data) {
        cerr << "ERROR: Invalid parameters!" << endl;
        return 1;
    }
    cout << "    Parameters validated successfully." << endl;

    auto &ctx_parms = context_data->parms();
    auto &coeff_mod = ctx_parms.coeff_modulus();
    size_t total_bits = 0;
    for (auto &m : coeff_mod) total_bits += m.bit_count();
    cout << "    coeff_modulus total bits: " << total_bits << endl;

    /*********************
     * KEY GENERATION
     *********************/
    cout << "\n[2] Generating keys..." << endl;
    cout << "    (No Galois keys needed — non-batched approach)" << endl;

    auto key_start = chrono::high_resolution_clock::now();

    KeyGenerator keygen(context);
    auto secret_key = keygen.secret_key();

    PublicKey public_key;
    keygen.create_public_key(public_key);

    RelinKeys relin_keys;
    keygen.create_relin_keys(relin_keys);

    auto key_end = chrono::high_resolution_clock::now();
    auto key_ms = chrono::duration_cast<chrono::milliseconds>(key_end - key_start).count();
    cout << "    Key generation done (" << key_ms << " ms)" << endl;

    Encryptor encryptor(context, public_key);
    Evaluator evaluator(context);
    Decryptor decryptor(context, secret_key);

    /*********************
     * ENCRYPT INPUT
     *********************/
    vector<uint64_t> input_values = {42, 17, 83, 5, 91, 33, 67, 12};
    size_t n = input_values.size();

    cout << "\n[3] Encrypting " << n << " values..." << endl;
    cout << "    Input: ";
    for (auto v : input_values) cout << v << " ";
    cout << endl;

    // Verify all values are in valid range [0, 128]
    for (auto v : input_values) {
        if (v > 128) {
            cerr << "ERROR: Value " << v << " exceeds max 128!" << endl;
            return 1;
        }
    }

    vector<Ciphertext> ct(n);
    for (size_t i = 0; i < n; i++) {
        encryptor.encrypt(make_scalar_plain(input_values[i]), ct[i]);
    }

    // Check initial noise budget
    cout << "    Initial noise budgets: ";
    for (size_t i = 0; i < n; i++) {
        cout << decryptor.invariant_noise_budget(ct[i]);
        if (i < n - 1) cout << ", ";
    }
    cout << " bits" << endl;

    /*********************
     * SINGLE CAS TEST
     *********************/
    cout << "\n[4] Quick test: single compare-and-swap on (42, 17)..." << endl;
    {
        Ciphertext test_a, test_b;
        encryptor.encrypt(make_scalar_plain(42), test_a);
        encryptor.encrypt(make_scalar_plain(17), test_b);

        size_t mults_before = ct_ct_mult_count;
        compare_and_swap(evaluator, test_a, test_b, relin_keys);
        size_t mults_per_cas = ct_ct_mult_count - mults_before;

        Plaintext pt_a, pt_b;
        decryptor.decrypt(test_a, pt_a);
        decryptor.decrypt(test_b, pt_b);

        // Decode: for scalar plaintexts, the constant term is the value
        // The hex string represents the polynomial; constant term is the value
        uint64_t val_a = 0, val_b = 0;
        if (pt_a.coeff_count() > 0) val_a = pt_a[0];
        if (pt_b.coeff_count() > 0) val_b = pt_b[0];

        cout << "    Result: (" << val_a << ", " << val_b << ")" << endl;
        cout << "    Ct-ct multiplications per CAS: " << mults_per_cas << endl;
        cout << "    Noise budget after CAS: "
             << decryptor.invariant_noise_budget(test_a) << ", "
             << decryptor.invariant_noise_budget(test_b) << " bits" << endl;

        if (val_a == 17 && val_b == 42) {
            cout << "    PASS: correctly swapped to (17, 42)" << endl;
        } else {
            cout << "    FAIL: expected (17, 42)" << endl;
        }
    }

    // Reset counter for the full sort
    ct_ct_mult_count = 0;

    /*********************
     * FULL BITONIC SORT
     *********************/
    cout << "\n[5] Running bitonic sort on 8 encrypted values..." << endl;

    auto sort_start = chrono::high_resolution_clock::now();
    bitonic_sort(evaluator, ct, relin_keys, decryptor);
    auto sort_end = chrono::high_resolution_clock::now();

    auto sort_ms = chrono::duration_cast<chrono::milliseconds>(sort_end - sort_start).count();
    size_t sort_mult_count = ct_ct_mult_count;  // save before equal-elements test

    /*********************
     * DECRYPT & VERIFY
     *********************/
    cout << "\n[6] Decrypting results..." << endl;

    vector<uint64_t> output(n);
    for (size_t i = 0; i < n; i++) {
        Plaintext pt;
        decryptor.decrypt(ct[i], pt);
        output[i] = (pt.coeff_count() > 0) ? pt[0] : 0;
    }

    cout << "    Output: ";
    for (auto v : output) cout << v << " ";
    cout << endl;

    // Verify sort
    vector<uint64_t> expected = input_values;
    sort(expected.begin(), expected.end());

    cout << "    Expected: ";
    for (auto v : expected) cout << v << " ";
    cout << endl;

    bool correct = (output == expected);
    cout << "    " << (correct ? "PASS" : "FAIL") << ": sort "
         << (correct ? "correct" : "INCORRECT") << endl;

    /*********************
     * BENCHMARK SUMMARY
     *********************/
    cout << "\n========================================" << endl;
    cout << "BENCHMARK SUMMARY" << endl;
    cout << "========================================" << endl;
    cout << "  Sort time:        " << sort_ms << " ms" << endl;
    cout << "  Ct-ct multiplies: " << sort_mult_count << endl;
    cout << "  Final noise budgets: ";
    for (size_t i = 0; i < n; i++) {
        cout << decryptor.invariant_noise_budget(ct[i]);
        if (i < n - 1) cout << ", ";
    }
    cout << " bits" << endl;

    /*********************
     * EQUAL ELEMENTS TEST
     *********************/
    cout << "\n[7] Test with equal elements: [5, 5, 3, 3, 1, 1, 7, 7]" << endl;
    {
        vector<uint64_t> eq_input = {5, 5, 3, 3, 1, 1, 7, 7};
        vector<Ciphertext> eq_ct(8);
        for (size_t i = 0; i < 8; i++) {
            encryptor.encrypt(make_scalar_plain(eq_input[i]), eq_ct[i]);
        }

        bitonic_sort(evaluator, eq_ct, relin_keys, decryptor);

        vector<uint64_t> eq_output(8);
        for (size_t i = 0; i < 8; i++) {
            Plaintext pt;
            decryptor.decrypt(eq_ct[i], pt);
            eq_output[i] = (pt.coeff_count() > 0) ? pt[0] : 0;
        }

        cout << "    Output: ";
        for (auto v : eq_output) cout << v << " ";
        cout << endl;

        vector<uint64_t> eq_expected = {1, 1, 3, 3, 5, 5, 7, 7};
        bool eq_correct = (eq_output == eq_expected);
        cout << "    " << (eq_correct ? "PASS" : "FAIL") << endl;
    }

    /*********************
     * CSV LOGGING
     *********************/
    {
        time_t now = time(nullptr);
        tm *local_time = localtime(&now);
        ostringstream timestamp;
        timestamp << put_time(local_time, "%Y-%m-%d %H:%M:%S");

        ofstream csv("benchmark_results.csv", ios::app);
        csv.seekp(0, ios::end);
        if (csv.tellp() == 0) {
            csv << "timestamp,algorithm,n,runtime_ms,ct_ct_multiplications,noise_budget_bits\n";
        }

        long min_noise = decryptor.invariant_noise_budget(ct[0]);
        for (size_t i = 1; i < n; i++) {
            long nb = decryptor.invariant_noise_budget(ct[i]);
            if (nb < min_noise) min_noise = nb;
        }

        csv << timestamp.str() << ","
            << "BitonicBFV_NonBatched" << ","
            << n << ","
            << sort_ms << ","
            << sort_mult_count << ","
            << min_noise << "\n";
        csv.close();
        cout << "\nLogged run to benchmark_results.csv" << endl;
    }

    return 0;
}
