#include <seal/seal.h>
#include <iostream>
#include <vector>
#include <chrono>
#include <fstream>
#include <ctime>
#include <iomanip>
#include <algorithm>
#include <numeric>

using namespace std;
using namespace seal;

/*******************************************
 * CONSTANTS
 *******************************************/
static const uint64_t PLAIN_MOD = 257;
static const uint64_t INV2 = 129;  // inverse of 2 mod 257

// Q(y) coefficients: sign(x) = x * Q(x^2) over Z_257
// 128 coefficients (degree 127 polynomial)
// Generated by compute_sign_poly.py
static const uint64_t Q_COEFFS[128] = {
    129, 189, 142,  98,  50,  17,  95, 247,
      0, 239, 101, 199,  92, 224,  16, 111,
      0, 153,  36,  93,  61,  93, 199,  87,
      0, 100, 148,  10, 136,  86, 151, 204,
      0, 240, 140, 191, 132,   1,  82, 245,
      0, 157,   8, 192, 102, 230,   0,  65,
      0, 238, 214,   3, 136,  43,  30,  35,
      0, 159,  96, 116, 193, 101, 164, 206,
      0, 116,  73, 188, 187, 172, 115,  96,
      0, 184, 169, 177, 118, 104,  56, 207,
      0,  49, 221,  83, 125,   8, 124, 209,
      0, 192,  91, 204, 216, 187,  97,  16,
      0, 104, 248,  52,  50, 157,  58,  46,
      0, 252, 115, 132,  80,   4,   6,  71,
      0, 236, 178,  26, 224,   5, 240,  82,
      0, 256, 126, 185, 197, 253,   8, 193
};

static const size_t Q_SIZE = 128;
static const size_t BABY_STEP = 8;
static const size_t NUM_GROUPS = Q_SIZE / BABY_STEP;  // 16

/*******************************************
 * GLOBAL COUNTERS
 *******************************************/
static size_t ct_ct_mult_count = 0;

/*******************************************
 * HELPERS
 *******************************************/

// Encode a single scalar value as a SEAL Plaintext (hex string)
Plaintext make_scalar_plain(uint64_t v) {
    v = v % PLAIN_MOD;
    // SEAL expects hex-encoded polynomial coefficients
    // For a scalar, just the constant term
    stringstream ss;
    ss << hex << v;
    return Plaintext(ss.str());
}

// Multiply ciphertext by ciphertext, relinearize, track count
void ct_mult(Evaluator &eval, const Ciphertext &a, const Ciphertext &b,
             Ciphertext &dest, const RelinKeys &rlk) {
    eval.multiply(a, b, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

// Square ciphertext, relinearize, track count
void ct_square(Evaluator &eval, const Ciphertext &a,
               Ciphertext &dest, const RelinKeys &rlk) {
    eval.square(a, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

/*******************************************
 * PATERSON-STOCKMEYER EVALUATION
 *
 * Shared helper: evaluates Q(y) where y = diff^2
 * using Paterson-Stockmeyer with baby step s=8.
 *
 * Returns {T, y} where T = Q(y) and y = diff^2.
 * Both eval_correction_poly and eval_flag_poly
 * call this, then apply their own Phase 4.
 *
 * Q has 128 coefficients, baby step s=8, 16 giant groups.
 *******************************************/
pair<Ciphertext, Ciphertext> eval_Q_of_y(Evaluator &eval,
                                          const Ciphertext &diff,
                                          const RelinKeys &rlk) {
    //--- Phase 1: Baby powers of y = diff^2 ---
    // We need y^0 (implicit), y^1, ..., y^7, and z = y^8
    Ciphertext y;  // y = diff^2
    ct_square(eval, diff, y, rlk);

    // Build baby powers: bp[0] = y, bp[1] = y^2, ..., bp[6] = y^7
    // Using a multiplication tree to minimize depth
    Ciphertext y2, y3, y4, y5, y6, y7, z;

    ct_square(eval, y, y2, rlk);          // y^2, depth 2 from diff
    ct_mult(eval, y, y2, y3, rlk);        // y^3, depth 3
    ct_square(eval, y2, y4, rlk);         // y^4, depth 3
    ct_mult(eval, y, y4, y5, rlk);        // y^5, depth 4
    ct_mult(eval, y2, y4, y6, rlk);       // y^6, depth 4
    ct_mult(eval, y3, y4, y7, rlk);       // y^7, depth 4
    ct_square(eval, y4, z, rlk);          // y^8 = z, depth 4

    // Array of baby powers for convenient indexing
    // baby[k] = y^(k+1) for k=0..6, so baby[k] corresponds to y^(k+1)
    // We also need y^0 = 1, which is just a plaintext addition (no ciphertext needed)
    vector<Ciphertext*> baby = {&y, &y2, &y3, &y4, &y5, &y6, &y7};

    //--- Phase 2: Compute B_i groups ---
    // B_i(y) = Q[8i] + Q[8i+1]*y + Q[8i+2]*y^2 + ... + Q[8i+7]*y^7
    // Each B_i involves only plaintext-ciphertext operations (no depth increase)
    vector<Ciphertext> B(NUM_GROUPS);

    for (size_t i = 0; i < NUM_GROUPS; i++) {
        size_t base = i * BABY_STEP;
        bool initialized = false;

        for (size_t j = 0; j < BABY_STEP; j++) {
            uint64_t coeff = Q_COEFFS[base + j];
            if (coeff == 0) continue;

            if (j == 0) {
                // Constant term: just a plaintext
                if (!initialized) {
                    // We need a ciphertext with value coeff
                    // Use multiply_plain on any baby power then add? No—
                    // We need to start with a plaintext-valued ciphertext.
                    // Actually we can't create an "encrypted constant" without
                    // encrypting. Instead, we'll handle the constant term specially.
                    // For now, mark that we have a constant and add it after.
                    // We'll accumulate all non-constant terms first, then add_plain.

                    // Actually, let's just use add_plain at the end.
                    // Start with the j=0 term as pending constant.
                    // Skip for now, handle below.
                    continue;
                }
            } else {
                // Term: coeff * y^j
                Ciphertext term;
                eval.multiply_plain(*baby[j - 1], make_scalar_plain(coeff), term);

                if (!initialized) {
                    B[i] = term;
                    initialized = true;
                } else {
                    eval.add_inplace(B[i], term);
                }
            }
        }

        // Add constant term (j=0) as plaintext
        uint64_t const_coeff = Q_COEFFS[base];
        if (const_coeff != 0) {
            if (!initialized) {
                // All higher terms were zero, B_i is just a constant.
                // We need a ciphertext. Multiply any baby power by 0 and add const?
                // Better: multiply y by 0 and add const, but multiply_plain by 0 may
                // cause issues. Instead, take y, multiply by the coefficient of the
                // first non-zero higher term... but we just said they're all zero.
                //
                // Edge case: B_i is a pure constant. We can't represent it as a
                // ciphertext without an encryption context. We'll handle this in
                // the Estrin tree by using add_plain instead.
                //
                // For simplicity, let's create a "zero ciphertext" by subtracting
                // a baby power from itself, then add_plain the constant.
                B[i] = y;  // copy
                eval.sub_inplace(B[i], y);  // B[i] = 0 (as ciphertext)
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
                initialized = true;
            } else {
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
            }
        }

        if (!initialized) {
            // Entire group is zero — create zero ciphertext
            B[i] = y;
            eval.sub_inplace(B[i], y);
        }
    }

    //--- Phase 3: Estrin tree to combine B_i using giant step z = y^8 ---
    // We have 16 groups: B[0] + z*B[1] + z^2*B[2] + ... + z^15*B[15]
    // Estrin tree: pair up and combine bottom-up using powers of z
    //
    // Level 0 (8 pairs): P_j = B[2j] + z * B[2j+1], j=0..7
    // Level 1 (4 pairs): R_j = P[2j] + z^2 * P[2j+1], j=0..3
    // Level 2 (2 pairs): S_j = R[2j] + z^4 * R[2j+1], j=0..1
    // Level 3 (1 pair):  T   = S[0]  + z^8 * S[1]

    // Level 0: 8 ct-ct multiplications
    vector<Ciphertext> P(8);
    for (size_t j = 0; j < 8; j++) {
        ct_mult(eval, z, B[2 * j + 1], P[j], rlk);
        eval.add_inplace(P[j], B[2 * j]);
    }

    // Compute z^2
    Ciphertext z2;
    ct_square(eval, z, z2, rlk);

    // Level 1: 4 ct-ct multiplications
    vector<Ciphertext> R(4);
    for (size_t j = 0; j < 4; j++) {
        ct_mult(eval, z2, P[2 * j + 1], R[j], rlk);
        eval.add_inplace(R[j], P[2 * j]);
    }

    // Compute z^4
    Ciphertext z4;
    ct_square(eval, z2, z4, rlk);

    // Level 2: 2 ct-ct multiplications
    vector<Ciphertext> S(2);
    for (size_t j = 0; j < 2; j++) {
        ct_mult(eval, z4, R[2 * j + 1], S[j], rlk);
        eval.add_inplace(S[j], R[2 * j]);
    }

    // Compute z^8
    Ciphertext z8;
    ct_square(eval, z4, z8, rlk);

    // Level 3: 1 ct-ct multiplication
    Ciphertext T;
    ct_mult(eval, z8, S[1], T, rlk);
    eval.add_inplace(T, S[0]);

    // T now holds Q(y)
    return {T, y};
}

/*******************************************
 * CORRECTION POLYNOMIAL
 *
 * correction = 129 * (diff + y * Q(y))
 * Returns diff if diff ∈ {1,...,128}, 0 otherwise
 *******************************************/
Ciphertext eval_correction_poly(Evaluator &eval,
                                const Ciphertext &diff,
                                const RelinKeys &rlk) {
    auto [T, y] = eval_Q_of_y(eval, diff, rlk);

    // Phase 4: correction = 129 * (diff + y * Q(y))
    Ciphertext yQ;
    ct_mult(eval, y, T, yQ, rlk);  // y * Q(y)

    Ciphertext inner;
    eval.add(diff, yQ, inner);  // diff + y * Q(y)

    // Multiply by 129 (inv(2) mod 257)
    Ciphertext correction;
    eval.multiply_plain(inner, make_scalar_plain(INV2), correction);

    return correction;
}

/*******************************************
 * FLAG POLYNOMIAL
 *
 * flag = 129 * (diff * Q(y) + 1)
 * Returns 1 if diff ∈ {1,...,128}, 0 otherwise
 *
 * Derivation: sign(x) = x * Q(x^2)
 *   = 1 for x ∈ {1,...,128}
 *   = -1 (=256) for x ∈ {129,...,256}
 *   = 0 for x = 0
 * flag = (sign + 1) / 2 = 129 * (sign + 1)
 *      = 129 * (x * Q(x^2) + 1)
 *******************************************/
Ciphertext eval_flag_poly(Evaluator &eval,
                          const Ciphertext &diff,
                          const RelinKeys &rlk) {
    auto [T, y] = eval_Q_of_y(eval, diff, rlk);

    // Phase 4: flag = 129 * (diff * Q(y) + 1)
    Ciphertext sign;
    ct_mult(eval, diff, T, sign, rlk);  // diff * Q(y), depth 9

    // sign + 1
    eval.add_plain_inplace(sign, make_scalar_plain(1));

    // Multiply by 129 (inv(2) mod 257)
    Ciphertext flag;
    eval.multiply_plain(sign, make_scalar_plain(INV2), flag);

    return flag;
}

/*******************************************
 * IS-ZERO INDICATOR
 *
 * Returns 1 if x encrypts 0, 0 otherwise.
 * Uses Fermat's little theorem: x^256 ≡ 1 (mod 257)
 * for x ≠ 0, so is_zero(x) = 1 - x^256.
 * When x = 0: 0^256 = 0, so 1 - 0 = 1. ✓
 * When x ≠ 0: x^256 = 1, so 1 - 1 = 0. ✓
 *
 * 8 ct-ct multiplications (squarings), depth 8 from input.
 *******************************************/
Ciphertext eval_is_zero(Evaluator &eval,
                        const Ciphertext &x,
                        const RelinKeys &rlk) {
    Ciphertext pow = x;
    for (int i = 0; i < 8; i++) {
        ct_square(eval, pow, pow, rlk);  // x^2, x^4, ..., x^256
    }
    eval.negate_inplace(pow);            // -x^256
    eval.add_plain_inplace(pow, make_scalar_plain(1));  // 1 - x^256
    return pow;
}

/*******************************************
 * COMPARE AND SWAP (ascending)
 *
 * If a > b: sets a = b, b = a (swap)
 * If a <= b: no change
 *
 * Uses correction polynomial:
 *   correction = diff if diff in {1,...,128}
 *   correction = 0    otherwise
 *******************************************/
void compare_and_swap(Evaluator &eval,
                      Ciphertext &ct_a, Ciphertext &ct_b,
                      const RelinKeys &rlk) {
    Ciphertext diff;
    eval.sub(ct_a, ct_b, diff);  // diff = a - b

    Ciphertext correction = eval_correction_poly(eval, diff, rlk);

    eval.sub_inplace(ct_a, correction);  // a - correction = min(a,b) if a>b
    eval.add_inplace(ct_b, correction);  // b + correction = max(a,b) if a>b
}

/*******************************************
 * BITONIC SORT (8 elements)
 *
 * Standard bitonic sorting network:
 * 6 rounds, 4 compare-and-swap per round,
 * 24 total CAS operations.
 *******************************************/
void bitonic_sort(Evaluator &eval,
                  vector<Ciphertext> &ct,
                  const RelinKeys &rlk,
                  Decryptor &decryptor) {
    size_t n = ct.size();
    int round = 0;

    for (size_t k = 2; k <= n; k <<= 1) {
        for (size_t j = k >> 1; j >= 1; j >>= 1) {
            round++;
            cout << "  Round " << round << " (k=" << k << ", j=" << j << "):" << endl;

            for (size_t i = 0; i < n; i++) {
                size_t l = i ^ j;
                if (l > i) {
                    bool ascending = ((i & k) == 0);
                    if (ascending) {
                        compare_and_swap(eval, ct[i], ct[l], rlk);
                    } else {
                        compare_and_swap(eval, ct[l], ct[i], rlk);
                    }
                }
            }

            // Print noise budget after each round
            cout << "    Noise budgets: ";
            for (size_t i = 0; i < n; i++) {
                cout << decryptor.invariant_noise_budget(ct[i]);
                if (i < n - 1) cout << ", ";
            }
            cout << " bits" << endl;
        }
    }
}

/*******************************************
 * RANK-BASED SORT
 *
 * Constant multiplicative depth (18) regardless
 * of array size. Only works with distinct inputs.
 *
 * Phase 1: Pairwise comparison flags
 *   flag_ij = 1 if ct[i] > ct[j], 0 otherwise
 * Phase 2: Compute ranks
 *   rank[i] = # elements smaller than ct[i]
 * Phase 3: Place elements at sorted positions
 *   output[k] = sum_i( ct[i] * is_zero(rank[i] - k) )
 *******************************************/
void rank_based_sort(Evaluator &eval,
                     vector<Ciphertext> &ct,
                     const RelinKeys &rlk,
                     Decryptor &decryptor) {
    size_t n = ct.size();

    // --- Phase 1: Pairwise comparison flags ---
    cout << "  Phase 1: Computing pairwise comparison flags..." << endl;

    // flags[i][j] stores flag(ct[i] - ct[j]) for i < j
    // flag_ij = 1 means ct[i] > ct[j]
    vector<vector<Ciphertext>> flags(n, vector<Ciphertext>(n));

    for (size_t i = 0; i < n; i++) {
        for (size_t j = i + 1; j < n; j++) {
            Ciphertext diff;
            eval.sub(ct[i], ct[j], diff);
            flags[i][j] = eval_flag_poly(eval, diff, rlk);
        }
    }

    cout << "    Noise budget after Phase 1: "
         << decryptor.invariant_noise_budget(flags[0][1]) << " bits" << endl;

    // --- Phase 2: Compute ranks ---
    // rank[i] = number of elements smaller than ct[i]
    //         = sum_{j != i} flag(ct[i] - ct[j])
    // For i < j: flag(ct[i] - ct[j]) = flags[i][j]       (contributes to rank[i])
    //            flag(ct[j] - ct[i]) = 1 - flags[i][j]    (contributes to rank[j])
    cout << "  Phase 2: Computing ranks..." << endl;

    vector<Ciphertext> rank_ct(n);

    for (size_t i = 0; i < n; i++) {
        bool initialized = false;

        for (size_t j = 0; j < n; j++) {
            if (i == j) continue;

            Ciphertext contribution;
            if (i < j) {
                // flag(ct[i] - ct[j]) = flags[i][j]
                contribution = flags[i][j];
            } else {
                // flag(ct[i] - ct[j]) = 1 - flags[j][i]
                contribution = flags[j][i];
                eval.negate_inplace(contribution);
                eval.add_plain_inplace(contribution, make_scalar_plain(1));
            }

            if (!initialized) {
                rank_ct[i] = contribution;
                initialized = true;
            } else {
                eval.add_inplace(rank_ct[i], contribution);
            }
        }
    }

    cout << "    Noise budget after Phase 2: "
         << decryptor.invariant_noise_budget(rank_ct[0]) << " bits" << endl;

    // --- Phase 3: Place elements at sorted positions ---
    // output[k] = sum_i( ct[i] * is_zero(rank[i] - k) )
    cout << "  Phase 3: Placing elements at sorted positions..." << endl;

    vector<Ciphertext> output(n);

    for (size_t k = 0; k < n; k++) {
        bool initialized = false;

        for (size_t i = 0; i < n; i++) {
            // Compute rank[i] - k
            Ciphertext rank_minus_k = rank_ct[i];
            if (k > 0) {
                eval.sub_plain(rank_ct[i], make_scalar_plain(k), rank_minus_k);
            }

            // is_zero(rank[i] - k)
            Ciphertext indicator = eval_is_zero(eval, rank_minus_k, rlk);

            // ct[i] * indicator
            Ciphertext term;
            ct_mult(eval, ct[i], indicator, term, rlk);

            if (!initialized) {
                output[k] = term;
                initialized = true;
            } else {
                eval.add_inplace(output[k], term);
            }
        }

        cout << "    Position " << k << " noise budget: "
             << decryptor.invariant_noise_budget(output[k]) << " bits" << endl;
    }

    // Copy output back to ct[]
    for (size_t i = 0; i < n; i++) {
        ct[i] = output[i];
    }
}

/*******************************************
 * SORT ALGORITHM ENUM
 *******************************************/
enum class SortAlgorithm {
    Bitonic,
    RankBased
};

/*******************************************
 * RUN ONE BENCHMARK
 *
 * Encrypts, sorts, decrypts, verifies, and
 * logs results for a given input array.
 *******************************************/
void run_benchmark(const vector<uint64_t> &input_values,
                   Encryptor &encryptor,
                   Evaluator &evaluator,
                   Decryptor &decryptor,
                   const RelinKeys &relin_keys,
                   SortAlgorithm algorithm = SortAlgorithm::Bitonic) {
    size_t n = input_values.size();

    string algo_name = (algorithm == SortAlgorithm::Bitonic)
                        ? "BitonicBFV_NonBatched"
                        : "RankBFV_NonBatched";

    cout << "\n========================================" << endl;
    cout << "Sorting " << n << " encrypted values (" << algo_name << ")" << endl;
    cout << "========================================" << endl;

    // Verify all values are in valid range [0, 128]
    for (auto v : input_values) {
        if (v > 128) {
            cerr << "ERROR: Value " << v << " exceeds max 128!" << endl;
            return;
        }
    }

    // Encrypt
    cout << "  Input:  ";
    for (auto v : input_values) cout << v << " ";
    cout << endl;

    vector<Ciphertext> ct(n);
    for (size_t i = 0; i < n; i++) {
        encryptor.encrypt(make_scalar_plain(input_values[i]), ct[i]);
    }

    cout << "  Initial noise budget: " << decryptor.invariant_noise_budget(ct[0]) << " bits" << endl;

    // Sort
    ct_ct_mult_count = 0;
    auto sort_start = chrono::high_resolution_clock::now();
    if (algorithm == SortAlgorithm::Bitonic) {
        bitonic_sort(evaluator, ct, relin_keys, decryptor);
    } else {
        rank_based_sort(evaluator, ct, relin_keys, decryptor);
    }
    auto sort_end = chrono::high_resolution_clock::now();

    auto sort_ms = chrono::duration_cast<chrono::milliseconds>(sort_end - sort_start).count();
    size_t mults = ct_ct_mult_count;

    // Decrypt and verify
    vector<uint64_t> output(n);
    for (size_t i = 0; i < n; i++) {
        Plaintext pt;
        decryptor.decrypt(ct[i], pt);
        output[i] = (pt.coeff_count() > 0) ? pt[0] : 0;
    }

    cout << "  Output: ";
    for (auto v : output) cout << v << " ";
    cout << endl;

    vector<uint64_t> expected = input_values;
    sort(expected.begin(), expected.end());

    bool correct = (output == expected);
    cout << "  " << (correct ? "PASS" : "FAIL") << endl;

    // Find min noise budget
    long min_noise = decryptor.invariant_noise_budget(ct[0]);
    for (size_t i = 1; i < n; i++) {
        long nb = decryptor.invariant_noise_budget(ct[i]);
        if (nb < min_noise) min_noise = nb;
    }

    cout << "  Sort time:        " << sort_ms << " ms" << endl;
    cout << "  Ct-ct multiplies: " << mults << endl;
    cout << "  Min noise budget: " << min_noise << " bits" << endl;

    // CSV logging
    time_t now = time(nullptr);
    tm *local_time = localtime(&now);
    ostringstream timestamp;
    timestamp << put_time(local_time, "%Y-%m-%d %H:%M:%S");

    ofstream csv("benchmark_results.csv", ios::app);
    csv.seekp(0, ios::end);
    if (csv.tellp() == 0) {
        csv << "timestamp,algorithm,n,runtime_ms,ct_ct_multiplications,noise_budget_bits,correct\n";
    }

    csv << timestamp.str() << ","
        << algo_name << ","
        << n << ","
        << sort_ms << ","
        << mults << ","
        << min_noise << ","
        << (correct ? "true" : "false") << "\n";
    csv.close();
}

/*******************************************
 * MAIN
 *******************************************/
int main() {
    cout << "========================================" << endl;
    cout << "Non-Batched BFV Sort Benchmark" << endl;
    cout << "========================================" << endl;

    /*********************
     * BFV PARAMETER SETUP
     *********************/
    cout << "\n[1] Setting up BFV parameters..." << endl;

    size_t poly_modulus_degree = 32768;

    EncryptionParameters parms(scheme_type::bfv);
    parms.set_poly_modulus_degree(poly_modulus_degree);
    // Need ~2200 bits for n=16 (10 rounds x ~220 bits/round).
    // 40 primes x 60 bits = 2400 bits.
    // sec_level_type::none needed since this exceeds tc128 limits for N=32768.
    parms.set_coeff_modulus(CoeffModulus::Create(poly_modulus_degree,
        {60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60}));
    parms.set_plain_modulus(PLAIN_MOD);

    SEALContext context(parms, true, sec_level_type::none);

    auto context_data = context.key_context_data();
    if (!context_data) {
        cerr << "ERROR: Invalid parameters!" << endl;
        return 1;
    }

    auto &ctx_parms = context_data->parms();
    auto &coeff_mod = ctx_parms.coeff_modulus();
    size_t total_bits = 0;
    for (auto &m : coeff_mod) total_bits += m.bit_count();
    cout << "    poly_modulus_degree = " << poly_modulus_degree << endl;
    cout << "    plain_modulus = " << PLAIN_MOD << endl;
    cout << "    coeff_modulus total bits: " << total_bits << endl;

    /*********************
     * KEY GENERATION
     *********************/
    cout << "\n[2] Generating keys..." << endl;

    auto key_start = chrono::high_resolution_clock::now();

    KeyGenerator keygen(context);
    auto secret_key = keygen.secret_key();

    PublicKey public_key;
    keygen.create_public_key(public_key);

    RelinKeys relin_keys;
    keygen.create_relin_keys(relin_keys);

    auto key_end = chrono::high_resolution_clock::now();
    auto key_ms = chrono::duration_cast<chrono::milliseconds>(key_end - key_start).count();
    cout << "    Key generation done (" << key_ms << " ms)" << endl;

    Encryptor encryptor(context, public_key);
    Evaluator evaluator(context);
    Decryptor decryptor(context, secret_key);

    /*********************
     * SINGLE CAS SANITY CHECK
     *********************/
    cout << "\n[3] Quick test: single compare-and-swap on (42, 17)..." << endl;
    {
        Ciphertext test_a, test_b;
        encryptor.encrypt(make_scalar_plain(42), test_a);
        encryptor.encrypt(make_scalar_plain(17), test_b);

        ct_ct_mult_count = 0;
        compare_and_swap(evaluator, test_a, test_b, relin_keys);

        Plaintext pt_a, pt_b;
        decryptor.decrypt(test_a, pt_a);
        decryptor.decrypt(test_b, pt_b);

        uint64_t val_a = (pt_a.coeff_count() > 0) ? pt_a[0] : 0;
        uint64_t val_b = (pt_b.coeff_count() > 0) ? pt_b[0] : 0;

        cout << "    Result: (" << val_a << ", " << val_b << ") — "
             << ((val_a == 17 && val_b == 42) ? "PASS" : "FAIL") << endl;
        cout << "    Ct-ct multiplications per CAS: " << ct_ct_mult_count << endl;
        cout << "    Noise budget after CAS: "
             << decryptor.invariant_noise_budget(test_a) << " bits" << endl;
    }

    /*********************
     * FLAG POLYNOMIAL SANITY CHECK
     *********************/
    cout << "\n[4] Quick test: flag polynomial..." << endl;
    {
        // flag(42 - 17) = flag(25) should be 1 (25 ∈ {1,...,128})
        Ciphertext ct_42, ct_17;
        encryptor.encrypt(make_scalar_plain(42), ct_42);
        encryptor.encrypt(make_scalar_plain(17), ct_17);

        Ciphertext diff_pos;
        evaluator.sub(ct_42, ct_17, diff_pos);
        ct_ct_mult_count = 0;
        Ciphertext flag_pos = eval_flag_poly(evaluator, diff_pos, relin_keys);

        Plaintext pt_flag;
        decryptor.decrypt(flag_pos, pt_flag);
        uint64_t flag_val = (pt_flag.coeff_count() > 0) ? pt_flag[0] : 0;
        cout << "    flag(42-17) = " << flag_val << " — "
             << ((flag_val == 1) ? "PASS" : "FAIL") << endl;
        cout << "    Ct-ct multiplications: " << ct_ct_mult_count << endl;
        cout << "    Noise budget: " << decryptor.invariant_noise_budget(flag_pos) << " bits" << endl;

        // flag(17 - 42) = flag(232) should be 0 (232 ∈ {129,...,256})
        Ciphertext diff_neg;
        evaluator.sub(ct_17, ct_42, diff_neg);
        Ciphertext flag_neg = eval_flag_poly(evaluator, diff_neg, relin_keys);

        decryptor.decrypt(flag_neg, pt_flag);
        flag_val = (pt_flag.coeff_count() > 0) ? pt_flag[0] : 0;
        cout << "    flag(17-42) = " << flag_val << " — "
             << ((flag_val == 0) ? "PASS" : "FAIL") << endl;
    }

    /*********************
     * IS-ZERO SANITY CHECK
     *********************/
    cout << "\n[5] Quick test: is_zero indicator..." << endl;
    {
        // is_zero(0) should be 1
        Ciphertext ct_zero;
        encryptor.encrypt(make_scalar_plain(0), ct_zero);
        ct_ct_mult_count = 0;
        Ciphertext iz_zero = eval_is_zero(evaluator, ct_zero, relin_keys);

        Plaintext pt_iz;
        decryptor.decrypt(iz_zero, pt_iz);
        uint64_t iz_val = (pt_iz.coeff_count() > 0) ? pt_iz[0] : 0;
        cout << "    is_zero(0) = " << iz_val << " — "
             << ((iz_val == 1) ? "PASS" : "FAIL") << endl;
        cout << "    Ct-ct multiplications: " << ct_ct_mult_count << endl;
        cout << "    Noise budget: " << decryptor.invariant_noise_budget(iz_zero) << " bits" << endl;

        // is_zero(5) should be 0
        Ciphertext ct_five;
        encryptor.encrypt(make_scalar_plain(5), ct_five);
        Ciphertext iz_five = eval_is_zero(evaluator, ct_five, relin_keys);

        decryptor.decrypt(iz_five, pt_iz);
        iz_val = (pt_iz.coeff_count() > 0) ? pt_iz[0] : 0;
        cout << "    is_zero(5) = " << iz_val << " — "
             << ((iz_val == 0) ? "PASS" : "FAIL") << endl;
    }

    /*********************
     * BENCHMARK: Rank-based sort n=4
     *********************/
    run_benchmark({42, 17, 83, 5},
                  encryptor, evaluator, decryptor, relin_keys,
                  SortAlgorithm::RankBased);

    // Bitonic sort benchmarks (commented out for now)
    // run_benchmark({42, 17},
    //               encryptor, evaluator, decryptor, relin_keys,
    //               SortAlgorithm::Bitonic);
    // run_benchmark({42, 17, 83, 5},
    //               encryptor, evaluator, decryptor, relin_keys,
    //               SortAlgorithm::Bitonic);
    // run_benchmark({42, 17, 83, 5, 91, 33, 67, 12},
    //               encryptor, evaluator, decryptor, relin_keys,
    //               SortAlgorithm::Bitonic);
    // run_benchmark({42, 17, 83, 5, 91, 33, 67, 12, 100, 2, 55, 28, 76, 9, 118, 44},
    //               encryptor, evaluator, decryptor, relin_keys,
    //               SortAlgorithm::Bitonic);

    cout << "\nAll benchmarks complete. Results in benchmark_results.csv" << endl;

    return 0;
}
