#include <seal/seal.h>
#include <iostream>
#include <vector>
#include <chrono>
#include <fstream>
#include <ctime>
#include <iomanip>
#include <algorithm>
#include <numeric>
#include <omp.h>
#include <atomic>

using namespace std;
using namespace seal;

/*******************************************
 * CONSTANTS
 *******************************************/
static const uint64_t PLAIN_MOD = 257;
static const uint64_t INV2 = 129;  // inverse of 2 mod 257

// Q(y) coefficients: sign(x) = x * Q(x^2) over Z_257
// 128 coefficients (degree 127 polynomial)
// Generated by compute_sign_poly.py
static const uint64_t Q_COEFFS[128] = {
    129, 189, 142,  98,  50,  17,  95, 247,
      0, 239, 101, 199,  92, 224,  16, 111,
      0, 153,  36,  93,  61,  93, 199,  87,
      0, 100, 148,  10, 136,  86, 151, 204,
      0, 240, 140, 191, 132,   1,  82, 245,
      0, 157,   8, 192, 102, 230,   0,  65,
      0, 238, 214,   3, 136,  43,  30,  35,
      0, 159,  96, 116, 193, 101, 164, 206,
      0, 116,  73, 188, 187, 172, 115,  96,
      0, 184, 169, 177, 118, 104,  56, 207,
      0,  49, 221,  83, 125,   8, 124, 209,
      0, 192,  91, 204, 216, 187,  97,  16,
      0, 104, 248,  52,  50, 157,  58,  46,
      0, 252, 115, 132,  80,   4,   6,  71,
      0, 236, 178,  26, 224,   5, 240,  82,
      0, 256, 126, 185, 197, 253,   8, 193
};

static const size_t Q_SIZE = 128;
static const size_t BABY_STEP = 8;
static const size_t NUM_GROUPS = Q_SIZE / BABY_STEP;  // 16

/*******************************************
 * GLOBAL COUNTERS
 *******************************************/
static atomic<size_t> ct_ct_mult_count{0};

/*******************************************
 * HELPERS
 *******************************************/

// Encode a single scalar value as a SEAL Plaintext (hex string)
Plaintext make_scalar_plain(uint64_t v) {
    v = v % PLAIN_MOD;
    stringstream ss;
    ss << hex << v;
    return Plaintext(ss.str());
}

// Multiply ciphertext by ciphertext, relinearize, track count
void ct_mult(Evaluator &eval, const Ciphertext &a, const Ciphertext &b,
             Ciphertext &dest, const RelinKeys &rlk) {
    eval.multiply(a, b, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

// Square ciphertext, relinearize, track count
void ct_square(Evaluator &eval, const Ciphertext &a,
               Ciphertext &dest, const RelinKeys &rlk) {
    eval.square(a, dest);
    eval.relinearize_inplace(dest, rlk);
    ct_ct_mult_count++;
}

/*******************************************
 * PATERSON-STOCKMEYER EVALUATION
 *
 * Shared helper: evaluates Q(y) where y = diff^2
 * using Paterson-Stockmeyer with baby step s=8.
 *
 * Returns {T, y} where T = Q(y) and y = diff^2.
 *
 * Q has 128 coefficients, baby step s=8, 16 giant groups.
 *******************************************/
pair<Ciphertext, Ciphertext> eval_Q_of_y(Evaluator &eval,
                                          const Ciphertext &diff,
                                          const RelinKeys &rlk) {
    //--- Phase 1: Baby powers of y = diff^2 ---
    Ciphertext y;  // y = diff^2
    ct_square(eval, diff, y, rlk);

    Ciphertext y2, y3, y4, y5, y6, y7, z;

    ct_square(eval, y, y2, rlk);          // y^2, depth 2 from diff
    ct_mult(eval, y, y2, y3, rlk);        // y^3, depth 3
    ct_square(eval, y2, y4, rlk);         // y^4, depth 3
    ct_mult(eval, y, y4, y5, rlk);        // y^5, depth 4
    ct_mult(eval, y2, y4, y6, rlk);       // y^6, depth 4
    ct_mult(eval, y3, y4, y7, rlk);       // y^7, depth 4
    ct_square(eval, y4, z, rlk);          // y^8 = z, depth 4

    vector<Ciphertext*> baby = {&y, &y2, &y3, &y4, &y5, &y6, &y7};

    //--- Phase 2: Compute B_i groups ---
    vector<Ciphertext> B(NUM_GROUPS);

    for (size_t i = 0; i < NUM_GROUPS; i++) {
        size_t base = i * BABY_STEP;
        bool initialized = false;

        for (size_t j = 0; j < BABY_STEP; j++) {
            uint64_t coeff = Q_COEFFS[base + j];
            if (coeff == 0) continue;

            if (j == 0) {
                if (!initialized) {
                    continue;
                }
            } else {
                Ciphertext term;
                eval.multiply_plain(*baby[j - 1], make_scalar_plain(coeff), term);

                if (!initialized) {
                    B[i] = term;
                    initialized = true;
                } else {
                    eval.add_inplace(B[i], term);
                }
            }
        }

        uint64_t const_coeff = Q_COEFFS[base];
        if (const_coeff != 0) {
            if (!initialized) {
                B[i] = y;  // copy
                eval.sub_inplace(B[i], y);  // B[i] = 0 (as ciphertext)
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
                initialized = true;
            } else {
                eval.add_plain_inplace(B[i], make_scalar_plain(const_coeff));
            }
        }

        if (!initialized) {
            B[i] = y;
            eval.sub_inplace(B[i], y);
        }
    }

    //--- Phase 3: Estrin tree to combine B_i using giant step z = y^8 ---
    // Level 0
    vector<Ciphertext> P(8);
    for (size_t j = 0; j < 8; j++) {
        ct_mult(eval, z, B[2 * j + 1], P[j], rlk);
        eval.add_inplace(P[j], B[2 * j]);
    }

    Ciphertext z2;
    ct_square(eval, z, z2, rlk);

    // Level 1
    vector<Ciphertext> R(4);
    for (size_t j = 0; j < 4; j++) {
        ct_mult(eval, z2, P[2 * j + 1], R[j], rlk);
        eval.add_inplace(R[j], P[2 * j]);
    }

    Ciphertext z4;
    ct_square(eval, z2, z4, rlk);

    // Level 2
    vector<Ciphertext> S(2);
    for (size_t j = 0; j < 2; j++) {
        ct_mult(eval, z4, R[2 * j + 1], S[j], rlk);
        eval.add_inplace(S[j], R[2 * j]);
    }

    Ciphertext z8;
    ct_square(eval, z4, z8, rlk);

    // Level 3
    Ciphertext T;
    ct_mult(eval, z8, S[1], T, rlk);
    eval.add_inplace(T, S[0]);

    return {T, y};
}

/*******************************************
 * FLAG POLYNOMIAL
 *
 * flag = 129 * (diff * Q(y) + 1)
 * Returns 1 if diff in {1,...,128}, 0 otherwise
 *******************************************/
Ciphertext eval_flag_poly(Evaluator &eval,
                          const Ciphertext &diff,
                          const RelinKeys &rlk) {
    auto [T, y] = eval_Q_of_y(eval, diff, rlk);

    Ciphertext sign;
    ct_mult(eval, diff, T, sign, rlk);  // diff * Q(y), depth 9

    eval.add_plain_inplace(sign, make_scalar_plain(1));

    Ciphertext flag;
    eval.multiply_plain(sign, make_scalar_plain(INV2), flag);

    return flag;
}

/*******************************************
 * IS-ZERO INDICATOR
 *
 * Returns 1 if x encrypts 0, 0 otherwise.
 * Uses Fermat's little theorem: x^256 = 1 (mod 257)
 * for x != 0, so is_zero(x) = 1 - x^256.
 *
 * 8 ct-ct multiplications (squarings), depth 8 from input.
 *******************************************/
Ciphertext eval_is_zero(Evaluator &eval,
                        const Ciphertext &x,
                        const RelinKeys &rlk) {
    Ciphertext pow = x;
    for (int i = 0; i < 8; i++) {
        ct_square(eval, pow, pow, rlk);
    }
    eval.negate_inplace(pow);
    eval.add_plain_inplace(pow, make_scalar_plain(1));
    return pow;
}

/*******************************************
 * RANK-BASED SORT (OpenMP parallelized)
 *
 * Constant multiplicative depth (18) regardless
 * of array size. Only works with distinct inputs.
 *
 * Phase 1: Pairwise comparison flags (parallelized)
 * Phase 2: Compute ranks (sequential — just additions)
 * Phase 3: Place elements at sorted positions (parallelized)
 *******************************************/
void rank_based_sort(Evaluator &eval,
                     vector<Ciphertext> &ct,
                     const RelinKeys &rlk,
                     Decryptor &decryptor) {
    size_t n = ct.size();

    // --- Phase 1: Pairwise comparison flags (parallelized) ---
    cout << "  Phase 1: Computing pairwise comparison flags..." << endl;

    vector<vector<Ciphertext>> flags(n, vector<Ciphertext>(n));

    // Flatten (i,j) pairs for parallel dispatch
    vector<pair<size_t, size_t>> pairs;
    for (size_t i = 0; i < n; i++)
        for (size_t j = i + 1; j < n; j++)
            pairs.push_back({i, j});

    #pragma omp parallel for schedule(dynamic)
    for (size_t idx = 0; idx < pairs.size(); idx++) {
        size_t i = pairs[idx].first;
        size_t j = pairs[idx].second;
        Ciphertext diff;
        eval.sub(ct[i], ct[j], diff);
        flags[i][j] = eval_flag_poly(eval, diff, rlk);
    }

    cout << "    Noise budget after Phase 1: "
         << decryptor.invariant_noise_budget(flags[0][1]) << " bits" << endl;

    // --- Phase 2: Compute ranks (sequential — trivial cost) ---
    cout << "  Phase 2: Computing ranks..." << endl;

    vector<Ciphertext> rank_ct(n);

    for (size_t i = 0; i < n; i++) {
        bool initialized = false;

        for (size_t j = 0; j < n; j++) {
            if (i == j) continue;

            Ciphertext contribution;
            if (i < j) {
                contribution = flags[i][j];
            } else {
                contribution = flags[j][i];
                eval.negate_inplace(contribution);
                eval.add_plain_inplace(contribution, make_scalar_plain(1));
            }

            if (!initialized) {
                rank_ct[i] = contribution;
                initialized = true;
            } else {
                eval.add_inplace(rank_ct[i], contribution);
            }
        }
    }

    cout << "    Noise budget after Phase 2: "
         << decryptor.invariant_noise_budget(rank_ct[0]) << " bits" << endl;

    // --- Phase 3: Place elements at sorted positions (parallelized) ---
    cout << "  Phase 3: Placing elements at sorted positions..." << endl;

    vector<Ciphertext> output(n);

    #pragma omp parallel for schedule(dynamic)
    for (size_t k = 0; k < n; k++) {
        bool initialized = false;

        for (size_t i = 0; i < n; i++) {
            Ciphertext rank_minus_k = rank_ct[i];
            if (k > 0) {
                eval.sub_plain(rank_ct[i], make_scalar_plain(k), rank_minus_k);
            }

            Ciphertext indicator = eval_is_zero(eval, rank_minus_k, rlk);

            Ciphertext term;
            ct_mult(eval, ct[i], indicator, term, rlk);

            if (!initialized) {
                output[k] = term;
                initialized = true;
            } else {
                eval.add_inplace(output[k], term);
            }
        }
    }

    // Print noise budgets sequentially after parallel region
    for (size_t k = 0; k < n; k++) {
        cout << "    Position " << k << " noise budget: "
             << decryptor.invariant_noise_budget(output[k]) << " bits" << endl;
    }

    // Copy output back to ct[]
    for (size_t i = 0; i < n; i++) {
        ct[i] = output[i];
    }
}

/*******************************************
 * RUN ONE BENCHMARK
 *******************************************/
void run_benchmark(const vector<uint64_t> &input_values,
                   Encryptor &encryptor,
                   Evaluator &evaluator,
                   Decryptor &decryptor,
                   const RelinKeys &relin_keys) {
    size_t n = input_values.size();
    string algo_name = "RankBFV_NonBatched_Parallel";

    cout << "\n========================================" << endl;
    cout << "Sorting " << n << " encrypted values (" << algo_name << ")" << endl;
    cout << "========================================" << endl;

    // Verify all values are in valid range [0, 128]
    for (auto v : input_values) {
        if (v > 128) {
            cerr << "ERROR: Value " << v << " exceeds max 128!" << endl;
            return;
        }
    }

    // Encrypt
    cout << "  Input:  ";
    for (auto v : input_values) cout << v << " ";
    cout << endl;

    vector<Ciphertext> ct(n);
    for (size_t i = 0; i < n; i++) {
        encryptor.encrypt(make_scalar_plain(input_values[i]), ct[i]);
    }

    cout << "  Initial noise budget: " << decryptor.invariant_noise_budget(ct[0]) << " bits" << endl;

    // Sort
    ct_ct_mult_count = 0;
    auto sort_start = chrono::high_resolution_clock::now();
    rank_based_sort(evaluator, ct, relin_keys, decryptor);
    auto sort_end = chrono::high_resolution_clock::now();

    auto sort_ms = chrono::duration_cast<chrono::milliseconds>(sort_end - sort_start).count();
    size_t mults = ct_ct_mult_count;

    // Decrypt and verify
    vector<uint64_t> output(n);
    for (size_t i = 0; i < n; i++) {
        Plaintext pt;
        decryptor.decrypt(ct[i], pt);
        output[i] = (pt.coeff_count() > 0) ? pt[0] : 0;
    }

    cout << "  Output: ";
    for (auto v : output) cout << v << " ";
    cout << endl;

    vector<uint64_t> expected = input_values;
    sort(expected.begin(), expected.end());

    bool correct = (output == expected);
    cout << "  " << (correct ? "PASS" : "FAIL") << endl;

    // Find min noise budget
    long min_noise = decryptor.invariant_noise_budget(ct[0]);
    for (size_t i = 1; i < n; i++) {
        long nb = decryptor.invariant_noise_budget(ct[i]);
        if (nb < min_noise) min_noise = nb;
    }

    cout << "  Sort time:        " << sort_ms << " ms" << endl;
    cout << "  Ct-ct multiplies: " << mults << endl;
    cout << "  Min noise budget: " << min_noise << " bits" << endl;

    // CSV logging
    time_t now = time(nullptr);
    tm *local_time = localtime(&now);
    ostringstream timestamp;
    timestamp << put_time(local_time, "%Y-%m-%d %H:%M:%S");

    ofstream csv("benchmark_results.csv", ios::app);
    csv.seekp(0, ios::end);
    if (csv.tellp() == 0) {
        csv << "timestamp,algorithm,n,runtime_ms,ct_ct_multiplications,noise_budget_bits,correct\n";
    }

    csv << timestamp.str() << ","
        << algo_name << ","
        << n << ","
        << sort_ms << ","
        << mults << ","
        << min_noise << ","
        << (correct ? "true" : "false") << "\n";
    csv.close();
}

/*******************************************
 * MAIN
 *******************************************/
int main() {
    cout << "========================================" << endl;
    cout << "Rank-Based BFV Sort (OpenMP Parallel)" << endl;
    cout << "========================================" << endl;
    cout << "OpenMP threads: " << omp_get_max_threads() << endl;

    /*********************
     * BFV PARAMETER SETUP
     *********************/
    cout << "\n[1] Setting up BFV parameters..." << endl;

    size_t poly_modulus_degree = 32768;

    EncryptionParameters parms(scheme_type::bfv);
    parms.set_poly_modulus_degree(poly_modulus_degree);
    // Rank-based sort: constant depth 18, ~430 bits noise consumed.
    // 40 primes x 60 bits = 2400 bits — gives generous headroom.
    // N=32768 — matches bitonic's ring size for fair comparison.
    parms.set_coeff_modulus(CoeffModulus::Create(poly_modulus_degree,
        {60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
         60, 60, 60, 60, 60, 60, 60, 60, 60, 60}));
    parms.set_plain_modulus(PLAIN_MOD);

    SEALContext context(parms, true, sec_level_type::none);

    auto context_data = context.key_context_data();
    if (!context_data) {
        cerr << "ERROR: Invalid parameters!" << endl;
        return 1;
    }

    auto &ctx_parms = context_data->parms();
    auto &coeff_mod = ctx_parms.coeff_modulus();
    size_t total_bits = 0;
    for (auto &m : coeff_mod) total_bits += m.bit_count();
    cout << "    poly_modulus_degree = " << poly_modulus_degree << endl;
    cout << "    plain_modulus = " << PLAIN_MOD << endl;
    cout << "    coeff_modulus total bits: " << total_bits << endl;

    /*********************
     * KEY GENERATION
     *********************/
    cout << "\n[2] Generating keys..." << endl;

    auto key_start = chrono::high_resolution_clock::now();

    KeyGenerator keygen(context);
    auto secret_key = keygen.secret_key();

    PublicKey public_key;
    keygen.create_public_key(public_key);

    RelinKeys relin_keys;
    keygen.create_relin_keys(relin_keys);

    auto key_end = chrono::high_resolution_clock::now();
    auto key_ms = chrono::duration_cast<chrono::milliseconds>(key_end - key_start).count();
    cout << "    Key generation done (" << key_ms << " ms)" << endl;

    Encryptor encryptor(context, public_key);
    Evaluator evaluator(context);
    Decryptor decryptor(context, secret_key);

    /*********************
     * FLAG POLYNOMIAL SANITY CHECK
     *********************/
    cout << "\n[3] Quick test: flag polynomial..." << endl;
    {
        Ciphertext ct_42, ct_17;
        encryptor.encrypt(make_scalar_plain(42), ct_42);
        encryptor.encrypt(make_scalar_plain(17), ct_17);

        Ciphertext diff_pos;
        evaluator.sub(ct_42, ct_17, diff_pos);
        ct_ct_mult_count = 0;
        Ciphertext flag_pos = eval_flag_poly(evaluator, diff_pos, relin_keys);

        Plaintext pt_flag;
        decryptor.decrypt(flag_pos, pt_flag);
        uint64_t flag_val = (pt_flag.coeff_count() > 0) ? pt_flag[0] : 0;
        cout << "    flag(42-17) = " << flag_val << " — "
             << ((flag_val == 1) ? "PASS" : "FAIL") << endl;
        cout << "    Ct-ct multiplications: " << ct_ct_mult_count << endl;
        cout << "    Noise budget: " << decryptor.invariant_noise_budget(flag_pos) << " bits" << endl;

        Ciphertext diff_neg;
        evaluator.sub(ct_17, ct_42, diff_neg);
        Ciphertext flag_neg = eval_flag_poly(evaluator, diff_neg, relin_keys);

        decryptor.decrypt(flag_neg, pt_flag);
        flag_val = (pt_flag.coeff_count() > 0) ? pt_flag[0] : 0;
        cout << "    flag(17-42) = " << flag_val << " — "
             << ((flag_val == 0) ? "PASS" : "FAIL") << endl;
    }

    /*********************
     * IS-ZERO SANITY CHECK
     *********************/
    cout << "\n[4] Quick test: is_zero indicator..." << endl;
    {
        Ciphertext ct_zero;
        encryptor.encrypt(make_scalar_plain(0), ct_zero);
        ct_ct_mult_count = 0;
        Ciphertext iz_zero = eval_is_zero(evaluator, ct_zero, relin_keys);

        Plaintext pt_iz;
        decryptor.decrypt(iz_zero, pt_iz);
        uint64_t iz_val = (pt_iz.coeff_count() > 0) ? pt_iz[0] : 0;
        cout << "    is_zero(0) = " << iz_val << " — "
             << ((iz_val == 1) ? "PASS" : "FAIL") << endl;
        cout << "    Ct-ct multiplications: " << ct_ct_mult_count << endl;
        cout << "    Noise budget: " << decryptor.invariant_noise_budget(iz_zero) << " bits" << endl;

        Ciphertext ct_five;
        encryptor.encrypt(make_scalar_plain(5), ct_five);
        Ciphertext iz_five = eval_is_zero(evaluator, ct_five, relin_keys);

        decryptor.decrypt(iz_five, pt_iz);
        iz_val = (pt_iz.coeff_count() > 0) ? pt_iz[0] : 0;
        cout << "    is_zero(5) = " << iz_val << " — "
             << ((iz_val == 0) ? "PASS" : "FAIL") << endl;
    }

    /*********************
     * BENCHMARK: Rank-based sort n=2,4,8,16
     *********************/
    run_benchmark({42, 17},
                  encryptor, evaluator, decryptor, relin_keys);

    run_benchmark({42, 17, 83, 5},
                  encryptor, evaluator, decryptor, relin_keys);

    run_benchmark({42, 17, 83, 5, 91, 33, 67, 12},
                  encryptor, evaluator, decryptor, relin_keys);

    run_benchmark({42, 17, 83, 5, 91, 33, 67, 12, 100, 2, 55, 28, 76, 9, 118, 44},
                  encryptor, evaluator, decryptor, relin_keys);

    cout << "\nAll benchmarks complete. Results in benchmark_results.csv" << endl;

    return 0;
}
